import Container from '@/components/shared/container'
import Navbar from '@/components/shared/navbar'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import localFont from 'next/font/local'
import { Toaster } from 'react-hot-toast'
import './globals.css'

// Local fonts
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

// Google font: Outfit
const outfit = Outfit({
	subsets: ['latin'],
	variable: '--font-outfit',
	weight: ['400', '700'], // Specify the weights you need
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<style>
					@import
					url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Playwrite+CU:wght@100..400&display=swap');
				</style>
			</head>
			<body className={`${outfit.variable} antialiased`}>
				<Navbar></Navbar>
				<Container>{children}</Container>
				<Toaster />
			</body>
		</html>
	)
}
